### ISSUE TITLE
Delete Button in User Management: 500 Server Error

### ISSUE THREAD

**Issue by SlothCroissant** [tidusjar/Ombi#1583]
#### Ombi build Version:

V 3.0.2125

#### Update Branch:

DotNetCore

#### Media Sever:

Plex

#### Operating System:

Docker running on Ombi: https://hub.docker.com/r/lsiodev/ombi-preview/

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

No log recorded for action, just appears to be some bootup logs from when the container starts just after 4AM:
```
2017-10-17 04:07:51.101 -05:00 [Information] Start installing Hangfire SQL objects...
2017-10-17 04:07:51.189 -05:00 [Information] Hangfire SQL objects installed.
2017-10-17 04:07:51.227 -05:00 [Information] Starting Hangfire Server
2017-10-17 04:07:51.231 -05:00 [Information] Using job storage: 'SQLite Server: /config/Ombi.db'
2017-10-17 04:07:51.232 -05:00 [Information] Using the following options for Hangfire Server:
2017-10-17 04:07:51.232 -05:00 [Information]     Worker count: 1
2017-10-17 04:07:51.232 -05:00 [Information]     Listening queues: 'default'
2017-10-17 04:07:51.233 -05:00 [Information]     Shutdown timeout: 00:00:15
2017-10-17 04:07:51.233 -05:00 [Information]     Schedule polling interval: 00:00:15
```

#### Problem Description:

When deleting a managed (local) user in User Management, Chrome devtools shows that the API request throws a 500 server error. This happens both with and without my nginx reverse proxy.

#### Reproduction Steps:

Attempt to delete local user.

**Comment by tidusjar** [comment]
Please verify you are on the latest build. As I can produce this on older builds but not the latest

**Comment by SlothCroissant** [comment]
The Ombi app says there is an update, but the lisodev Docker preview isn't pulling the latest.

Will just wait for that to finally get an update, and it should be fixed. Thanks!

**Comment by tidusjar** [comment]
Restart the container, it pulls the latest version on restart!

**Comment by SlothCroissant** [comment]
Yep, did that, it still pulls `3.0.2125-DotNetCore`:

```
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 44.3M  100 44.3M    0     0  1227k      0  0:00:37  0:00:37 --:--:-- 1338k
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Hello, welcome to Ombi
Valid options are:
Ombi 3.0.2125-DotNetCore
Copyright (C) 2017 Ombi

  -h, --host       (Default: http://*:5000) Set to a semicolon-separated (;)
                   list of URL prefixes to which the server should respond. For
                   example, http://localhost:123. Use "*" to indicate that the
                   server should listen for requests on any IP address or
                   hostname using the specified port and protocol (for example,
                   http://*:5000). The protocol (http:// or https://) must be
                   included with each URL. Supported formats vary between
                   servers.

  -s, --storage    Storage path, where we save the logs and database

  --help           Display this help screen.

  --version        Display version information.
```

**Comment by tidusjar** [comment]
Still an issue?

**Comment by Codehhh** [comment]
This is still an issue for me with the most recent build. The user I am trying to delete is a Ombi created user.

![image](https://user-images.githubusercontent.com/12055335/31691663-d05d8e38-b364-11e7-824c-9a0bb4ed0453.png)

**Comment by SlothCroissant** [comment]
The docker image did upgrade after you asked above, but I still see 500 errors, with and without reverse proxy.

**Comment by tidusjar** [comment]
Interesting, can you create an admin user for me @SlothCroissant and email me your database and include in the email what user you are trying to delete? tidusjar@gmail.com

**Comment by SlothCroissant** [comment]
Email sent.
