### ISSUE TITLE
Notification for new issues

### ISSUE THREAD

**Issue by cesalo** [tidusjar/Ombi#1914]
#### Ombi build Version:
V 3.0.2731
#### Update Branch:
Open Beta
#### Media Sever:
Plex - 1.11.0.4666
#### Operating System:
Docker
#### Problem Description:
1. I'm not getting notification for new issues.
2. When issues are solved users are not getting notified (Not sure if this feature is available).
#### Reproduction Steps:
User create an issue.
No notification is sent out.
Issue solved.
No notification is sent out.

**Comment by tidusjar** [comment]
Regarding the 1st one, When a user creates an issue, a notification should get sent out. Can you please check your logs?

Also make sure it's enabled on the right hand side of your notifications.

**Comment by gadgetusaf** [comment]
Errors
fail: Ombi.Notifications.NotificationService[4000]
      Failed to notify for notification: Ombi.Notifications.Agents.EmailNotification
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Notifications.NotificationMessageCurlys.Setup(NotificationOptions opts, FullBaseRequest req, CustomizationSettings s) in C:\projects\requestplex\src\Ombi.Notifications\NotificationMessageCurlys.cs:line 15
   at Ombi.Notifications.Interfaces.BaseNotification`1.Parse(NotificationOptions model, NotificationTemplates template) in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 159
   at Ombi.Notifications.Interfaces.BaseNotification`1.<LoadTemplate>d__34.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Agents.EmailNotification.<LoadTemplate>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Agents.EmailNotification.<NewIssue>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__30.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 82

**Comment by tidusjar** [comment]
@gadgetusaf try latest build

**Comment by gadgetusaf** [comment]
I just updated to the latest beta build and that is what I got. I updated ~2 hours ago.

**Comment by tidusjar** [comment]
There is a newer build

**Comment by gadgetusaf** [comment]
updated and my errors are below.
 Currently on - 	3.0.2757
fail: Ombi.Notifications.NotificationService[4000]
      Failed to notify for notification: Ombi.Notifications.Agents.EmailNotification
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Notifications.NotificationMessageCurlys.Setup(NotificationOptions opts, FullBaseRequest req, CustomizationSettings s) in C:\projects\requestplex\src\Ombi.Notifications\NotificationMessageCurlys.cs:line 15
   at Ombi.Notifications.Interfaces.BaseNotification`1.Parse(NotificationOptions model, NotificationTemplates template) in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 159
   at Ombi.Notifications.Interfaces.BaseNotification`1.<LoadTemplate>d__34.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Agents.EmailNotification.<LoadTemplate>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Agents.EmailNotification.<NewIssue>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__30.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 82

**Comment by cesalo** [comment]
I'm uisng 3.0.2757 and it's not working. New issues doesn't send an e-mail - I do get e-mails when somebody request a movie / tv-show.

**Comment by cesalo** [comment]
And just confirming that is enable:

![image](https://user-images.githubusercontent.com/16859916/35296236-6fc7d182-0049-11e8-8b51-8e75dd22b394.png)

**Comment by tidusjar** [comment]
@cesalo like I said above, please post your logs.

**Comment by cesalo** [comment]
@tidusjar I can't find any relevant error/message in /config/Logs. How do I enable debug mode? I was searching the settings but can't find it. I'm using the docker image .. where is the config file to do it manually?
Thanks.

**Comment by tidusjar** [comment]
It should be in the docker Logs

**Comment by ceptonit** [comment]
Same issue here.

Docker log:
`fail: Ombi.Notifications.NotificationService[4000]
      Failed to notify for notification: Ombi.Notifications.Agents.EmailNotification
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Notifications.NotificationMessageCurlys.Setup(NotificationOptions opts, FullBaseRequest req, CustomizationSettings s) in C:\projects\requestplex\src\Ombi.Notifications\NotificationMessageCurlys.cs:line 16
   at Ombi.Notifications.Interfaces.BaseNotification`1.Parse(NotificationOptions model, NotificationTemplates template) in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 159
   at Ombi.Notifications.Interfaces.BaseNotification`1.<LoadTemplate>d__34.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Agents.EmailNotification.<LoadTemplate>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Agents.EmailNotification.<NewIssue>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__30.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 82`

**Comment by tidusjar** [comment]
I pushed a new build with more error logging. Can you please try this and post the logs.

Thanks

**Comment by ceptonit** [comment]
I can't seem to find the 2859 build

**Comment by tidusjar** [comment]
my bad, new build has been fixed.

**Comment by ceptonit** [comment]
Doesn't look like there's more info in the logs.
On 3.0.2860 build.

`fail: Ombi.Notifications.NotificationService[4000]
      Failed to notify for notification: Ombi.Notifications.Agents.EmailNotification
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Notifications.NotificationMessageCurlys.Setup(NotificationOptions opts, FullBaseRequest req, CustomizationSettings s) in C:\projects\requestplex\src\Ombi.Notifications\NotificationMessageCurlys.cs:line 16
   at Ombi.Notifications.Interfaces.BaseNotification`1.Parse(NotificationOptions model, NotificationTemplates template) in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 165
   at Ombi.Notifications.Interfaces.BaseNotification`1.<LoadTemplate>d__35.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Agents.EmailNotification.<LoadTemplate>d__10.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Agents.EmailNotification.<NewIssue>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__32.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 82`

**Comment by tidusjar** [comment]
@ceptonit are you able to send me your `ombi.db` so I can debug this to see what is going on? Looks like it's not doing what I expect.

If you don't mind, can you create a local admin user and then email me the credentials for the user and the db file @ tidusjar@gmail.com ?

**Comment by ceptonit** [comment]
@tidusjar Sent.

**Comment by tidusjar** [comment]
This is still broken when resolving issues.

**Comment by rulles** [comment]
Hello,

I try the last release (3.0.2863) and when someone open an Issue, the notification is send to admin, but, the variable `{RequestedUser}` going empty, so in the email, not show what user open issue.

Another thing, if admin user post a new comment in opened issue, the notification should be send to requested user and vice-versa. But what appends, it always send to admin, never for user.

The "Mark resolved" not send notification too, here the logs:
Feb  8 10:12:47 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Notifications.Agents.EmailNotification[0]
Feb  8 10:12:47 requests Ombi: Notification options: Ombi.Notifications.Models.NotificationOptions, Req: (null), Settings: Ombi.Settings.Settings.Models.CustomizationSettings
Feb  8 10:12:47 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Notifications.Agents.EmailNotification[0]
Feb  8 10:12:47 requests Ombi: Notification options: Ombi.Notifications.Models.NotificationOptions, Req: (null), Settings: Ombi.Settings.Settings.Models.CustomizationSettings
Feb  8 10:12:47 requests Ombi: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.Notifications.NotificationService[4000]
Feb  8 10:12:48 requests Ombi: Failed to notify for notification: Ombi.Notifications.Agents.EmailNotification
Feb  8 10:12:48 requests Ombi: System.NullReferenceException: Object reference not set to an instance of an object.
Feb  8 10:12:48 requests Ombi: at Ombi.Notifications.Agents.EmailNotification.<IssueResolved>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 164
Feb  8 10:12:48 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  8 10:12:48 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  8 10:12:48 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  8 10:12:48 requests Ombi: at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__32.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 100
Feb  8 10:12:48 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  8 10:12:48 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  8 10:12:48 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  8 10:12:48 requests Ombi: at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 50
Feb  8 10:12:48 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  8 10:12:48 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  8 10:12:48 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  8 10:12:48 requests Ombi: at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 82

**Comment by rulles** [comment]
Hello,

Have another issue i realized, with version 3.0.2863 the email notification for requests is not send to admin user. Here the logs:
Feb  8 12:03:05 requests Ombi: Searching : The Little Vampire
Feb  8 12:03:06 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Core.Engine.MovieSearchEngine[0]
Feb  8 12:03:06 requests Ombi: Search Result: Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult
Feb  8 12:03:23 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Notifications.Agents.EmailNotification[0]
Feb  8 12:03:23 requests Ombi: Notification options: Ombi.Notifications.Models.NotificationOptions, Req: Ombi.Store.Entities.Requests.MovieRequests, Settings: Ombi.Settings.Settings.Models.CustomizationSettings
Feb  8 12:03:23 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Notifications.Agents.EmailNotification[0]
Feb  8 12:03:23 requests Ombi: Notification options: Ombi.Notifications.Models.NotificationOptions, Req: Ombi.Store.Entities.Requests.MovieRequests, Settings: Ombi.Settings.Settings.Models.CustomizationSettings
Feb  8 12:03:23 requests Ombi: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.Notifications.GenericEmailProvider[0]
Feb  8 12:03:23 requests Ombi: Exception when attempting to send email
Feb  8 12:03:23 requests Ombi: System.ArgumentNullException: Value can not be null.
Feb  8 12:03:23 requests Ombi: at EnsureThat.EnsureArg.IsNotNull[T](T value, String paramName)
Feb  8 12:03:23 requests Ombi: at EnsureThat.EnsureArg.IsNotNullOrEmpty(String value, String paramName)
Feb  8 12:03:23 requests Ombi: at Ombi.Notifications.GenericEmailProvider.<Send>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 104
Feb  8 12:03:23 requests Ombi: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.Notifications.NotificationService[4000]
Feb  8 12:03:23 requests Ombi: Failed to notify for notification: Ombi.Notifications.Agents.EmailNotification
Feb  8 12:03:23 requests Ombi: System.ArgumentNullException: Value can not be null.
Feb  8 12:03:23 requests Ombi: at EnsureThat.EnsureArg.IsNotNull[T](T value, String paramName)
Feb  8 12:03:23 requests Ombi: at EnsureThat.EnsureArg.IsNotNullOrEmpty(String value, String paramName)
Feb  8 12:03:23 requests Ombi: at Ombi.Notifications.GenericEmailProvider.<Send>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 154
Feb  8 12:03:23 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  8 12:03:23 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  8 12:03:23 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  8 12:03:23 requests Ombi: at Ombi.Notifications.Agents.EmailNotification.<Send>d__21.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 260
Feb  8 12:03:23 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  8 12:03:23 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  8 12:03:23 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  8 12:03:23 requests Ombi: at Ombi.Notifications.Agents.EmailNotification.<NewRequest>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 111
Feb  8 12:03:23 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  8 12:03:23 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  8 12:03:23 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  8 12:03:23 requests Ombi: at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__32.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 79
Feb  8 12:03:23 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  8 12:03:23 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  8 12:03:23 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  8 12:03:23 requests Ombi: at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 50
Feb  8 12:03:23 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  8 12:03:23 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  8 12:03:23 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  8 12:03:23 requests Ombi: at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 82
Feb  8 12:03:24 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Notifications.Agents.EmailNotification[0]
Feb  8 12:03:24 requests Ombi: Notification options: Ombi.Notifications.Models.NotificationOptions, Req: Ombi.Store.Entities.Requests.MovieRequests, Settings: Ombi.Settings.Settings.Models.CustomizationSettings
Feb  8 12:03:24 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Notifications.Agents.EmailNotification[0]
Feb  8 12:03:24 requests Ombi: Notification options: Ombi.Notifications.Models.NotificationOptions, Req: Ombi.Store.Entities.Requests.MovieRequests, Settings: Ombi.Settings.Settings.Models.CustomizationSettings

**Comment by tidusjar** [comment]
@rulles do you have everything filled out in your email settings?

**Comment by rulles** [comment]
Yes, I have everything filled out and all types of notifications enable.
Like i have before.

**Comment by rulles** [comment]
Hello.

You mark this issue as closed in `2df8091`, but already have the last version (3.0.2865) and the problems remains.

**Comment by tidusjar** [comment]
When i commit and refrence the issue. Github will close the issue if the commit details contains the word "Fixed".

I thought the issue was fixed, can you please provide new logs?

**Comment by rulles** [comment]
I already give the logs in my 3º post before.

here the logs:
Feb  9 11:44:52 requests Ombi: Searching : thank you for service
Feb  9 11:44:52 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Core.Engine.MovieSearchEngine[0]
Feb  9 11:44:52 requests Ombi: Search Result: Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult
Feb  9 11:45:09 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Notifications.Agents.EmailNotification[0]
Feb  9 11:45:10 requests Ombi: Notification options: Ombi.Notifications.Models.NotificationOptions, Req: Ombi.Store.Entities.Requests.MovieRequests, Settings: Ombi.Settings.Settings.Models.CustomizationSettings
Feb  9 11:45:10 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Notifications.Agents.EmailNotification[0]
Feb  9 11:45:10 requests Ombi: Notification options: Ombi.Notifications.Models.NotificationOptions, Req: Ombi.Store.Entities.Requests.MovieRequests, Settings: Ombi.Settings.Settings.Models.CustomizationSettings
Feb  9 11:45:11 requests Ombi: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.Notifications.GenericEmailProvider[0]
Feb  9 11:45:11 requests Ombi: Exception when attempting to send email
Feb  9 11:45:11 requests Ombi: System.ArgumentNullException: Value can not be null.
Feb  9 11:45:11 requests Ombi: at EnsureThat.EnsureArg.IsNotNull[T](T value, String paramName)
Feb  9 11:45:11 requests Ombi: at EnsureThat.EnsureArg.IsNotNullOrEmpty(String value, String paramName)
Feb  9 11:45:11 requests Ombi: at Ombi.Notifications.GenericEmailProvider.<Send>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 104
Feb  9 11:45:11 requests Ombi: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Ombi.Notifications.NotificationService[4000]
Feb  9 11:45:11 requests Ombi: Failed to notify for notification: Ombi.Notifications.Agents.EmailNotification
Feb  9 11:45:11 requests Ombi: System.ArgumentNullException: Value can not be null.
Feb  9 11:45:11 requests Ombi: at EnsureThat.EnsureArg.IsNotNull[T](T value, String paramName)
Feb  9 11:45:11 requests Ombi: at EnsureThat.EnsureArg.IsNotNullOrEmpty(String value, String paramName)
Feb  9 11:45:11 requests Ombi: at Ombi.Notifications.GenericEmailProvider.<Send>d__6.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 154
Feb  9 11:45:11 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  9 11:45:11 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  9 11:45:11 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  9 11:45:11 requests Ombi: at Ombi.Notifications.Agents.EmailNotification.<Send>d__21.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 262
Feb  9 11:45:11 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  9 11:45:11 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  9 11:45:11 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  9 11:45:11 requests Ombi: at Ombi.Notifications.Agents.EmailNotification.<NewRequest>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Agents\EmailNotification.cs:line 111
Feb  9 11:45:11 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  9 11:45:11 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  9 11:45:11 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  9 11:45:11 requests Ombi: at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__32.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 79
Feb  9 11:45:11 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  9 11:45:11 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  9 11:45:11 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  9 11:45:11 requests Ombi: at Ombi.Notifications.Interfaces.BaseNotification`1.<NotifyAsync>d__31.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\Interfaces\BaseNotification.cs:line 50
Feb  9 11:45:11 requests Ombi: --- End of stack trace from previous location where exception was thrown ---
Feb  9 11:45:11 requests Ombi: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb  9 11:45:11 requests Ombi: at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb  9 11:45:11 requests Ombi: at Ombi.Notifications.NotificationService.<NotifyAsync>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Notifications\NotificationService.cs:line 82
Feb  9 11:45:12 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Notifications.Agents.EmailNotification[0]
Feb  9 11:45:12 requests Ombi: Notification options: Ombi.Notifications.Models.NotificationOptions, Req: Ombi.Store.Entities.Requests.MovieRequests, Settings: Ombi.Settings.Settings.Models.CustomizationSettings
Feb  9 11:45:12 requests Ombi: #033[40m#033[37mdbug#033[39m#033[22m#033[49m: Ombi.Notifications.Agents.EmailNotification[0]
Feb  9 11:45:12 requests Ombi: Notification options: Ombi.Notifications.Models.NotificationOptions, Req: Ombi.Store.Entities.Requests.MovieRequests, Settings: Ombi.Settings.Settings.Models.CustomizationSettings

**Comment by tidusjar** [comment]
The reason I am asking for new logs is since the code has changed and the exception has changed.

**Comment by rulles** [comment]
Ok,

That are the last logs from the last request. The user receive the the approval request email but the admin not receive the request email.

I remember that problem with comments in issues is still active, if admin comment the issue, the email is sent to admin instead to the user.

The tag `{RequestedUser}` in issues notification is empty.

**Comment by tidusjar** [comment]
Yes that makes sense since it's an issue and not the request, if `{RequestedUser}` worked then it would be the user that requested the content and not the person who raised the issue. I plan to improve and add more variables to support this.

**Comment by tidusjar** [comment]
@rulles  I just tried the New Request email and I could not find any issues,

I did however find the issue with the Issue Comment and I have now fixed that.

I have also added some new variables you can see here: https://github.com/tidusjar/Ombi/wiki/Notification-Template-Variables

In particular `{IssueUser}`

**Comment by rulles** [comment]
Hello,

I tried your last version (3.0.2878) and now, everything looks fine.

Only one or two things to inform:

1º the tag `{IssueCategory}` goes empty in emails notifications.

2º in email notifications templates, have one template without title.
print: 
![image](https://user-images.githubusercontent.com/14089574/36052678-8e0815f8-0de6-11e8-9fd0-a245ab8dd365.png)
is the template for comments in issues.

3º when the admin hit "Mark in Progress" an issue, maybe is nice send a notification to the user.

4º last and already spoked, the possibility of organize the order of requests.

In my opinion, this is the most important stuff for now. i not realized more none issue at the moment.
