### ISSUE TITLE
Some posters do not load due to unsupported size.

### ISSUE THREAD

**Issue by CorneliousJD** [tidusjar/Ombi#1932]
#### Ombi build Version:

V 3.0.2772

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Operating System:

unRAID/Docker Container (LSIO)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-01-27 12:08:58.911 -05:00 [Debug] Searching : "pottersville"
2018-01-27 12:08:58.954 -05:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult"

```

#### Problem Description:

When searching some movies, e.g. Pottersville, the poster shows as a broken link. 
When going directly to the URL for hte poster (https://image.tmdb.org/t/p/w150//zlQgswQ5GEklrbv8MkohQHyomZu.jpg) it shows image size is not supported.

#### Reproduction Steps:

Search around for random movies until you find one with a broken image link, then inspect the element in Chrome to find the URL and go to it, it seems they aren't serving some posters based on size, changing w150 to w500 will cause it to display properly.

**Comment by jeramie72** [comment]
i have found the same issue with some movies, haven't noticed any tv series having the problem yet.  
Winchester is a good example.  
Winchester (2018):
https://image.tmdb.org/t/p/w150//1GStpZZjj4fgl8RUq1mZ9X992GI.jpg 
fails to load with a image size is not supported.  

Winchester '73 (1950):
https://image.tmdb.org/t/p/w150//3t2X0rCcn6wxkOva06Io0NFkxYp.jpg
loads fine

i'm running on windows 2012 r2 DotNetcore 3.0.2772, i'll update now and see if it helps.

**Comment by vortexrap** [comment]
I'm also having this issue, but since the error is being displayed on the tmdb site, is this an issue on their end? or is ombi requesting a poster resize and there is some issue causing an incorrect poster generation?

**Comment by jeramie72** [comment]
i wonder if version 2 of ombi had the same issue? i'm new to Ombi.

**Comment by vortexrap** [comment]
I'm seeing https://github.com/tidusjar/Ombi/issues/675 but the issue says the issue was resolved with an application update. Just might be that v3 beta the fix is not working or not deployed.

**Comment by CorneliousJD** [comment]
Perhaps developer could work around this by requesting w300 instead of w150, as everything that's showed as broken that I've looked at (albeit, a small sample set) loads with w300 in the URL instead, and then just do the resize to a 150 width image from within Ombi itself? 

This means that all movie posters would get requested as w300 instead of w150, but then ombi could display them at the proper size?

**Comment by jeramie72** [comment]
@CorneliousJD great discovery, i looked deeper and so far w154 works fine

**Comment by tidusjar** [comment]
We may still have the same issue when movies don't have a w300 size

**Comment by jeramie72** [comment]
@tidusjar i changed w150 to w154 in google inspect for all the elements on a result page and it seems to work fine.  Like CorneliousJD it was a small sample set, but that might be a super easy fix.

**Comment by YodaSpow** [comment]
>@jeramie72: i wonder if version 2 of ombi had the same issue? i'm new to Ombi.

I'm running:
Application Version: | 2.2.1678
OS: | Mono
System Version: | 4.6.2 (Debian 4.6.2.7+dfsg-1)
Branch: | Stable

Same issue:

```
<div class="col-sm-2">
  <img class="img-responsive" src="https://image.tmdb.org/t/p/w150//iwapgsiyOLFZCrzDmdspdkrbkIW.jpg" alt="poster">
 </div>
```

**Comment by goku-son** [comment]
I am running 2.2.1678 using Plex 1.11.1.4760. Running on Windows 10. I too have noticed this problem as of late and like @jeramie72 mentioned I can get the image to display using w154. I see this request was closed and there appears to be a fix for it but going to w300. Is there a specific file(s) us v2 users can make the changes in if we have the 2.2.1678 source? I do not see the html files where these changes were made on my system so that's why I ask. Thanks in advance!

**Comment by tidusjar** [comment]
You'd need to make the changes in a v2 fork and potentially recompile ombi

**Comment by goku-son** [comment]
Thanks @tidusjar. So just to confirm this issue is fixed in v3 but no plans to fix in v2 since you are not doing any development for v2? Was just holding off until the newsletter became available in v3. Any rough idea on when that will be available? Thanks in advance!

**Comment by ortizdr** [comment]
I found where to update the template. Go to the location of Ombi's root and than "views\search".
Open "index.cshtml", search for all locations that have "150" and replace with "154". Save and restart Ombi. You should now be good to go!

**Comment by goku-son** [comment]
@ortizdr I want to thank you for your tip! That did the trick!!! Now I can continue to enjoy v2 while waiting on the v3 newsletter. Thanks again!

**Comment by ortizdr** [comment]
Glad I could help! I’m a newb so I’m glad I found a solution that someone else could replicate!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by YodaSpow** [comment]
Thanks, 
Done all the tweaks - I know how to startup the Ombi on my SSH setup:
`exec ~/Ombi/Release/Ombi.exe`

Just how do you restart it, if its running?

I'm running:
Application Version: | 2.2.1678
OS: | Mono
System Version: | 4.6.2 (Debian 4.6.2.7+dfsg-1)
Branch: | Stable

**Comment by ortizdr** [comment]
I’m running it on Windows. I couldn’t tell you. What about just rebooting the machine or VM?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leifi76** [comment]
@ortizdr your solution worked perfectly! Thanks :)

**Comment by ortizdr** [comment]
@leifi76 Glad I could be of assistance!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by YodaSpow** [comment]
@ortizdr - thanks alot is been working with this fix after restart to Ombi. Had it working for a week or so. Brilliant fix

**Comment by Spidergear** [comment]
You have to to the same to Views/Requests/Index.cshtml.
My posters on the requests page were not showing as well.

**Comment by tidusjar** [comment]
Or just use V3

**Comment by Spidergear** [comment]
is V3 available in a container yet?

**Comment by Spidergear** [comment]
Never mind.. found it!

https://hub.docker.com/r/lsiodev/ombi-preview/

**Comment by ChiPaulMichaels** [comment]
I'm on v3.0.2607 and still have this exact issue. What version is it fixed in?

**Comment by tidusjar** [comment]
A lot later. Stable is currently v3.0.3173

**Comment by ChiPaulMichaels** [comment]
Very odd.. I just had it check and it told me it's up to date/running the latest version.

**Comment by tidusjar** [comment]
The auto updater. Yes upgrade manually for now

**Comment by ChiPaulMichaels** [comment]
Gotcha, good to know, thanks. Just upgraded.
