### ISSUE TITLE
Adding Movie / TV Show to Radarr / Sonarr fails

### ISSUE THREAD

**Issue by galli-leo** [tidusjar/Ombi#1985]
#### Ombi build Version:

V 3.0.2896

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Linux 6ec679bbc2bb 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux (Probably Ubuntu 14.04 or 17.17, not sure since using a docker image).

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-02-17 10:19:45.940 +00:00 [Error] Exception thrown when attempting to send series over to Sonarr
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Sonarr.Models.CommandResult' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.<Request>d__6`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Sonarr.SonarrApi.<Command>d__16.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Sonarr.SonarrApi.<SeasonSearch>d__14.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Core.Senders.TvSender.<SearchForRequest>d__27.MoveNext() in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 362
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Core.Senders.TvSender.<SendToSonarr>d__25.MoveNext() in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 269
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Core.Senders.TvSender.<SendToSonarr>d__24.MoveNext() in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 187

2018-02-17 10:02:45.566 +00:00 [Error] Error When adding movie to Radarr
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Radarr.Models.RadarrAddMovieResponse' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Radarr.RadarrApi.<AddMovie>d__14.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Radarr\RadarrApi.cs:line 111
```

#### Problem Description:

When adding either a movie or a tv series, Ombi fails to add them to Radarr or Sonarr respectively. See above log snippet, I am guessing some json serialization fails for the response.

#### Reproduction Steps:

1. Add Radarr / Sonarr as Movie / TV Shows provider
2. Add a movie / a tv show
3. It doesn't show up in Radarr / Sonarr :(

**Comment by bcsteeve** [comment]
Yeah same.  I just installed Ombi and I thought I was doing something wrong, but I'm pretty sure I have everything dialed in and I get no errors and everything confirms connections are good... but nothing actually "works" in Radarr or Sonarr.  I haven't tried anything else because those are the only two I use.

**Comment by tidusjar** [comment]
Can't seem to recreate these issues, can you confirm the Sonarr/Radarr version and the branch?

I've pushed some changes but I don't think it will fix it, but if you could upgrade and see if it does that would be excellent.

**Comment by galli-leo** [comment]
Radarr is on develop with .935, Sonarr not so sure. Will check when I get home.

**Comment by tidusjar** [comment]
Thanks!

**Comment by galli-leo** [comment]
So updated Sonarr to latest master version and it still cannot add any shows, this time it's a different error though:
```
2018-02-19 15:02:24.701 +00:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.1.3:8989/api/series/0
2018-02-19 15:02:24.761 +00:00 [Error] Exception thrown when attempting to send series over to Sonarr
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Ombi.Api.Sonarr.SonarrApi.<GetSeriesById>d__7.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Core.Senders.TvSender.<SendToSonarr>d__24.MoveNext() in C:\projects\requestplex\src\Ombi.Core\Senders\TvSender.cs:line 179
```
For some reason docker image isn't updated yet and cannot update inside the docker, so cannot test the update version :(

**Comment by tidusjar** [comment]
That's fine, i'll see if I can reproduce when I get home from work, thanks for the help

**Comment by tidusjar** [comment]
Was there a specific movie this happened on for Radarr?

**Comment by galli-leo** [comment]
Hmm I tried The Nut Job and Olaf's Frozen Adventure. (Just to test things out). Also seems like caching the Radarr library went fine, as it already knows what's available / already requested and in Radarr.

**Comment by tidusjar** [comment]
Hmmm, I cannot seem to recreate the issue, I requested The Nut Job and it sent it to Radarr with no issues. is the base url setup in the Ombi settings? (If radarr is on a base url)

**Comment by galli-leo** [comment]
Hmm that might be the issue. While I setup Radarr with the local ip, it does have a base url set. Will check it out tomorrow.

**Comment by bcsteeve** [comment]
So just an update from my perspective.

When I first installed, it seemed to work.  Then it just... didn't.  Today I decided to reinstall fresh and again it seems to work.  I added a movie request and then I went to Radarr and saw that it picked it up.  I went to SAB and saw that it was downloading.  When finished I saw it was finished in Radarr and it shows up in Plex.  All good!  But... the request still shows as "Processing Request".  I realize I can manually mark it as available, but that seems... like it should be necessary.

**Comment by tidusjar** [comment]
That's a different issue I am working on.

**Comment by bcsteeve** [comment]
OK.  I also have to correct myself.  For the *movie* it did eventually mark as available.  I'm not sure why the delay or what precipitated the change.   TV show, however, still shows as unavailable when it is.

**Comment by tidusjar** [comment]
Yes. As I stated above the is an open issue for that that I am working on

**Comment by bcsteeve** [comment]
Yes. As I stated above... just correcting myself  :)

**Comment by galli-leo** [comment]
Yep base url was the issue for me, interestingly that the test & quality profiles still worked.
