### ISSUE TITLE
Ombi not loading through NGINX

### ISSUE THREAD

**Issue by zeieri** [tidusjar/Ombi#2430]
#### Ombi build Version:

V 3.0.3477

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

Ubuntu LTS 18.04 (Bionic Beaver)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Couldn't find where to pull logs. If needed, we can work through that.

```

#### Problem Description:

When trying to reach Ombi via NGINX, it doesn't work. Gets stuck at "Loading...". Here is the NGINX Config:

> server {
> # The IP that you forwarded in your router (nginx proxy)
> 
> # Make site accessible from http://localhost/
>   server_name domain.local www.domain.local;
> 
> location / {
>         proxy_pass              http://IPofMainSiteBox;
>         proxy_set_header        X-Real-IP  $remote_addr;
>         proxy_set_header        Host            $host;
>         proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header        X-Forwarded-Proto https;
>         proxy_redirect off;
>     }
> 
> 
> location /requests {
>         proxy_pass                 http://IPofOmbiHost:5000/requests/login;
>         proxy_max_temp_file_size   0;
>         proxy_set_header           X-Real-IP  $remote_addr;
>         proxy_set_header           Host            $host;
>         proxy_set_header           X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header           X-Forwarded-Proto https;
>         proxy_read_timeout         90;
>         proxy_redirect off;
>     }
> 
>     listen 443 ssl; # managed by Certbot
>     ssl_certificate /etc/letsencrypt/live/domain.local/fullchain.pem; # managed by Certbot
>     ssl_certificate_key /etc/letsencrypt/live/domain.local/privkey.pem; # managed by Certbot
>     include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
>     ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
> 
> 
> }
> 
> 
> server {
>     if ($host = www.domain.local) {
>         return 301 https://$host$request_uri;
>     } # managed by Certbot
> 
> 
>     if ($host = domain.local) {
>         return 301 https://$host$request_uri;
>     } # managed by Certbot
> 
> 
>   listen IPofWebServer:80 default_server;
>   server_name domain.local www.domain.local;
>     return 404; # managed by Certbot
> 
> }

I also tried using "http://IPofOmbiHost:5000" for the ProxyPass but that gave me nothing. The base URL in Ombi is set to "/requests".

#### Reproduction Steps:

When trying to access https://domain.local/requests, I get:

![image](https://user-images.githubusercontent.com/36149372/43689947-f81cb1ca-98be-11e8-9095-b7173954adee.png)

**Comment by Do-while-Bacon** [comment]
Not sure if this is still the case, but I vaguely recall that using a base URL of /requests would break _everything_.

So, try a different base URL and see how that goes.

**Comment by zeieri** [comment]
I tried "/ombi" in both the nginx config and ombi application. Same issue... Is ombi not supposed to work either?

**Comment by Do-while-Bacon** [comment]
Well, it was worth a shot. Here is my config -- see if yours works with it. You may need the rewrite portion.

```
        location /plexreq/ {
            proxy_pass http://127.0.0.1:5000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection keep-alive;
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
        if ($http_referer ~* /plexreq/) {
            rewrite ^/dist/(.*) $scheme://$host/plexreq/dist/$1 permanent;
        }
```

**Comment by zeieri** [comment]
I tried the following config:

location /ombi/ {
        proxy_pass                 http://IPofOmbiHost:5000;
        proxy_max_temp_file_size   0;
        proxy_set_header           X-Real-IP  $remote_addr;
        proxy_set_header           Host            $host;
        proxy_set_header           X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header           X-Forwarded-Proto https;
        proxy_read_timeout         90;
        proxy_redirect off;
    }
	if ($http_referer ~* /ombi/) {
    rewrite ^/dist/(.*) $scheme://$host/ombi/dist/$1 permanent;
    }

And the following config:

location /ombi/ {
            proxy_pass http://IPofOmbiHost:5000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection keep-alive;
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
        if ($http_referer ~* /ombi/) {
            rewrite ^/dist/(.*) $scheme://$host/ombi/dist/$1 permanent;
        }

Neither worked.... So then I tried your exact configuration:

        location /plexreq/ {
            proxy_pass http://IPofOmbiHost:5000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection keep-alive;
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
        if ($http_referer ~* /plexreq/) {
            rewrite ^/dist/(.*) $scheme://$host/plexreq/dist/$1 permanent;
        }

I set the base URL to "/plexreq" and "/plexreq/" and got a Bad Gateway-502 message.

It's like Ombi can't be read by NGINX or isn't passing the correct information along...

**Comment by zeieri** [comment]
After fiddling some more with the configs, I got it to load to /plexreq/login/ but then nothing comes up. What's worse is that when I load it locally, I just get blank screens with the top bar.

**Comment by zeieri** [comment]
UPDATE: I turned off oAuth:

![image](https://user-images.githubusercontent.com/36149372/43814660-c3116aea-9a88-11e8-8d49-8c2d49dfbbca.png)

Everything works through the webserver from there. Oh, I restarted the service and the half loading pages issue was solved too.

**Comment by shibbidydibbidy** [comment]
i am having this problem I can not get ombi to load through nginx I disabled "enable Plex OAuth" but it is still not working

**Comment by zeieri** [comment]
Is your base url set to the same thing in NGINX and Ombi?

**Comment by shibbidydibbidy** [comment]
Ok. I never forwarded my ports in my router. Once I forwarded the ports 5000 to 80 and 443 it worked. I thought I didn’t need to because that’s what nginx was doing? Is that correct?

**Comment by zeieri** [comment]
You are correct. You should only need to forward the appropriate HTTP port (80 or 443 for SSL) to the IP address of your web services host. From there, NGINX displays the correct page based on the requested address.

Can you post your NGINX config for this address? I'd like to see that you are start and proceed with more if necessary. Also, to confirm, the URL for your NGINX location matches the base URL in the configuration of Ombi?

**Comment by shibbidydibbidy** [comment]
ok so im new at all of this. can i remove the stuff with the hashtags as thats being commented out?
and my base url in ombi configuration is set to /ombi

#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  bombflix.us 192.168.1.6;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
        root    "C:\docroot";
        index   index.php index.html index.htm;
        }

        location /ombi {

    	proxy_pass http://127.0.0.1:5000;
    	proxy_set_header Host $host;
   	proxy_set_header X-Real-IP $remote_addr;
   	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


     #HTTPS server
    
    server {
        listen       443 ssl; 
        server_name  bombflix.us;

        ssl_certificate       C:/docroot/bombflix.us.pem;
        ssl_certificate_key   C:/docroot/bombflix.us.key;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
            proxy_pass http://127.0.0.1:5000;
    		proxy_set_header Host $host;
   		proxy_set_header X-Real-IP $remote_addr;
   		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

}

**Comment by zeieri** [comment]
Your base URL is the problem. You can't use OMBI or REQUESTS. Try something else and see if that works.

**Comment by shibbidydibbidy** [comment]
ok. one more thing. so when i forward ports80 and 443 i can go to my website by entering my url bombflix.us or i can get to it by entering my private ip address in a browser. this doesnt seem secure. is that ok  or is there a security risk involved there

**Comment by zeieri** [comment]
What's not secure? Every website is accessible by IP address. That's the norm. If you don't have SSL enabled, disable port 443. You only need the ports you use to be open. As a general security measure, never open more then you need.

Also, never externally face a site that has no login without adding some kind of authentication in front of it.

**Comment by zeieri** [comment]
Have to change it in NGINX. If you don't, you will get a mismatch. With some apps (like sonarr), you get nothing. With Ombi, you get the loading page then nothing.

**Comment by shibbidydibbidy** [comment]
ok. i guess my conern is why use nginx if i am able to login to my ip address:port# without it? 
Also it seems like /ombi loads the most of the page. everything else i load is loading to blank pages or only the top black bar loads
Thank you for being so helpful. I am just learning how all of this works.

**Comment by shibbidydibbidy** [comment]
It's all up and running with a custom Base URL. thanks for all your help! i guess i just need to learn more about networking! i noticed thats how people log in to watch plex. they can just enter my ip and port # that plex is on and the plex app opens.

**Comment by zeieri** [comment]
Your IP address can change at the discretion of your ISP. So you setup dynamic DNS with an auto-updater inside your network so your DNS always works. That way you don't need to know your IP address all the time.

/Ombi is used when the application runs. So when you set /Ombi, it tries /Ombi/Ombi on some things which breaks the app.

You open port 32400 (among other things) to your Plex server to allow Plex to operate. As a result, yes people may go straight to your server. I recommend against it if you have lots of people. Plex.tv works perfectly fine and takes on part of the hosting load. Additionally, your ISP seeing direct IP traffic (with high bitrates for streaming) may block you. All depends on where you are and what governs your ISP.

I think if someone localhost's your Plex server (uses the IP:port), it messes up your watched/unwatched data (unless it prompts them to login). I'm not 100% on that though as I only use locahost when troubleshooting something. I've never streamed from it.

Hopefully that helps!
