### ISSUE TITLE
Plex User Importer not importing new users

### ISSUE THREAD

**Issue by HeroXx** [tidusjar/Ombi#2910]
**Describe the bug**
Plex User Importer does not work for new users.

The new user is a friend and not a home/family user.

**To Reproduce**

I'm not really able to give clear reproduction steps for this as I have only just noticed it no longer importing new users.

**Expected behavior**
Expected outcome is that new users are imported everyday or shortly after forcing the job to run.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
There are no errors in the logs that suggest that the user importer task is failing.

**Ombi Version (please complete the following information):**
- Version 3.0.4351
- Media Server Plex
- Docker

**Additional context**

**Comment by tidusjar** [comment]
Unfortunately I am going to need more information. If you trigger the job you should be able to view your docker logs and something will be in there.

**Comment by Deanosim** [comment]
I'm having the exact same problem, I'm also not getting any errors in my logs,

**Comment by tidusjar** [comment]
Is your Plex settings all correct? Since Ombi need to be able to talk to Plex to get the information

**Comment by Twiggy159** [comment]
I’m also having this issue. I don’t have anything in my logs either. 

When I try to manually run the importer I get no notification of it running or any errors. It just appears that the button does nothing.

**Comment by pdjames14** [comment]
having same issue ombi and plex work completely fine together, all other features are working perfectly with sonarr and radarr, only it seems that clicking the user import button does nothing, it just highlights and never gives a notification or error or anthing. checked all logs in docker, ombi, plex. Nothing shows up, its just acting like the button doesnt work.

**Comment by Twiggy159** [comment]
To add an update to this issue, it looks like the Plex User Importer just isn’t running at all. The job is supposed to run at 18:00 daily but it looks like it’s not even doing that. I have a new user since early last week on Plex that hasn’t shown up in Ombi yet.

**Comment by tidusjar** [comment]
Can everyone make sure it they state it's also not working for me, to include the Ombi version.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

**Comment by 2fst4u** [comment]
I'm on version 3.0.4522 and I'm unfortunately getting this issue. No "success" banner or anything. Plex connectivity is fine as I can test it and safe it successfully.

**Comment by Rexios80** [comment]
So this was fixed on April 6, but the latest release was on February 19. When are you planning to release this fix? It's a core feature that I need for my workflow.

**Comment by tidusjar** [comment]
I'll release it to master once I feel like the Dev build is stable enough. 

If this is a core feature you need then I suggest you switch to the develop branch. If you do not want to do that then I suggest you wait.

**Comment by Rexios80** [comment]
Unfortunately I cannot update to the develop branch because I’m using a managed installation provided by my hosting provider. I guess I’ll just have to wait.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Spass1966** [comment]
@tidusjar This still doesn't work even in the latest develop:
```
2019-07-22 15:55:08.042 +02:00 [Debug] Calling Execute on job Emby.IEmbyUserImporter
2019-07-22 15:55:08.043 +02:00 [Debug] Trigger instruction : DeleteTrigger
2019-07-22 15:55:08.043 +02:00 [Debug] Deleting trigger
2019-07-22 15:55:08.417 +02:00 [Error] Job Plex.IPlexUserImporter threw an unhandled Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexUserImporter.cs:line 65
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2019-07-22 15:55:08.417 +02:00 [Error] Job Plex.IPlexUserImporter threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexUserImporter.cs:line 65
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexUserImporter.cs:line 65
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
2019-07-22 15:55:08.418 +02:00 [Debug] Trigger instruction : DeleteTrigger
2019-07-22 15:55:08.419 +02:00 [Debug] Deleting trigger
2019-07-22 15:55:33.994 +02:00 [Debug] Batch acquisition of 0 triggers
2019-07-22 15:55:59.043 +02:00 [Debug] Batch acquisition of 0 triggers
2019-07-22 15:56:27.566 +02:00 [Debug] Batch acquisition of 0 triggers
```

**Comment by tidusjar** [comment]
This issue is closed. If you have an issue please open a new one. Closed issues are not usually monitored

**Comment by Spass1966** [comment]
@tidusjar I'm just trying to help you. I already have my users created so it's no big deal to me but if you want to take a look. you've got the logs.
