### ISSUE TITLE
Watcher integration not completing fully

### ISSUE THREAD

**Issue by WilliamJBrown** [tidusjar/Ombi#878]
#### Ombi Version:

V 	2.0.1178

#### Update Branch:

Development

#### Operating System:

Docker with rogueosb's container

#### Mono Version (only if your not on windows)

4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

System.NullReferenceException: Object reference not set to an instance of an object at Ombi.Core.MovieSender.SendToWatcher (Ombi.Store.RequestedModel model, Ombi.Core.SettingModels.WatcherSettings settings) <0x40338130 + 0x000e6> in :0 at Ombi.Core.MovieSender+d__14.MoveNext () <0x403376f0 + 0x00497> in :0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fc5b78018a0 + 0x00029> in :0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fc5b77ff880 + 0x000a7> in :0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fc5b77ff800 + 0x0006b> in :0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fc5b77ff7b0 + 0x0003a> in :0 at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fc5b77ffaa0 + 0x00017> in :0 at Ombi.UI.Modules.SearchModule+d__97.MoveNext () <0x40e7d810 + 0x01cae> in :0

```

`Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Ombi.Api.Models.Watcher.WatcherListStatusResult]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly. To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object. Path 'movies', line 2, position 10. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) <0x40912a80 + 0x00cc3> in :0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) <0x40912080 + 0x000cf> in :0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, Boolean checkAdditionalContent) <0x4090e4f0 + 0x001e3> in :0	`

`Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0. at Newtonsoft.Json.JsonTextReader.ParseValue () <0x4090fee0 + 0x00497> in :0 at Newtonsoft.Json.JsonTextReader.Read () <0x4090f900 + 0x0004b> in :0 at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () <0x4090f650 + 0x00013> in :0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, Boolean hasConverter) <0x4090f200 + 0x00087> in :0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, Boolean checkAdditionalContent) <0x4090e4f0 + 0x000d7> in :0	`

Apologise about the logs as I do not think there is a way for me define a log directory using the docker container. 

#### Problem Description:

I am just testing the waters with watcher integration. I understand its development branch and am just looking to give some more information that will better help you in getting this to work for you and every one. I request the movie with Watcher enabled and its says something went wrong in the top right. The movie is not saved as being requested in the admin page. Cannot approve the movie as it isn't on the admins requests page. The movie is successfully passed to Watcher. I guess Watcher is not returning results for ombi to read to see if it was successful or not.  

#### Reproduction Steps:

Requesting movies with Watcher enabled causes no movie to be added to the requests page. The movie is however sent to Watcher and it does search and grab the movie on Watchers end. 

Hopefully this will help in some way :)

**Comment by WilliamJBrown** [comment]
Never mind, did not fill in the base url field. This has now solved my issue.

**Comment by WilliamJBrown** [comment]
adding a base url causes it to look successful on OMBI's end but nothing has been sent to Watcher. When the base url is empty it sends something the Watcher but nothing happens on OMBI's end. Doesn't appear requested. Will try and find more logs for you.

**Comment by WilliamJBrown** [comment]
`Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Ombi.Api.Models.Watcher.WatcherListStatusResult]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly. To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object. Path 'movies', line 2, position 10. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) <0x40912a80 + 0x00cc3> in :0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) <0x40912080 + 0x000cf> in :0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, Boolean checkAdditionalContent) <0x4090e4f0 + 0x001e3> in :0	`

**Comment by tidusjar** [comment]
The API has changed...

**Comment by WilliamJBrown** [comment]
Ah I thought it was as simple as that. Just wanted to make you aware thats all not a big issue. I am sure watcher will be changing a lot.

**Comment by tidusjar** [comment]
I've spoken to the developer, it won't be changing existing endpoints. Just adding new ones which won't break the integration. So I'll redo the ombi bit and I'll update this

**Comment by tidusjar** [comment]
Updated EAP, should work now

**Comment by tidusjar** [comment]
The new Early Access Preview branch contains a finished version.

**Comment by calebcall** [comment]
With the new Early Access Preview branch (version 2.0.1186) now it can't connect to Watcher at all.  With version 2.0.1183, it would report an error that something went wrong and spit back the json error output above but it would actually connect and send the request.  Now it won't even do that.

**Comment by tidusjar** [comment]
you running latest watcher?

**Comment by calebcall** [comment]
I was one release behind.  Just updated to the latest but the problem still exists.  I tried to re-generate a new api key in Watcher, but that didn't fix it either.

**Comment by calebcall** [comment]
Just looked in the plexrequest logs when I make connection attempt and I get the following:

```2017/01/06 10:21:49.142 Ombi.Api.ApiRequest Error: System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000d1] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0019b] in <bd46d4d4f7964dfa9beea098499ab597>:0
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00064] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) [0x00000] in <a413af11872d4786add172686a6728e8>:0  System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000d1] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0019b] in <bd46d4d4f7964dfa9beea098499ab597>:0
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00064] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) [0x00000] in <a413af11872d4786add172686a6728e8>:0
2017/01/06 10:21:49.147 Ombi.Api.PlexApi Error: Exception when calling GetLibrarySections for Plex, Retrying 00:00:05 Ombi.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000d1] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0019b] in <bd46d4d4f7964dfa9beea098499ab597>:0
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00064] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <bd46d4d4f7964dfa9beea098499ab597>:0
  at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) [0x00000] in <a413af11872d4786add172686a6728e8>:0
   --- End of inner exception stack trace ---
  at Ombi.Api.ApiRequest.ExecuteXml[T] (RestSharp.IRestRequest request, System.Uri baseUri) [0x0003b] in <ce1f937b62f7475f924d2599bc9f7d3f>:0
  at Ombi.Api.PlexApi+<>c__DisplayClass18_0.<GetLibrarySections>b__0 () [0x0000b] in <ce1f937b62f7475f924d2599bc9f7d3f>:0
  at Polly.Policy+<>c__DisplayClass8_0`1[TResult].<Execute>b__0 () [0x00000] in <1b91e1eef2dd437f82921fe10cfdfe86>:0
  at Polly.RetrySyntax+<>c__DisplayClass14_0.<WaitAndRetry>b__1 () [0x00000] in <1b91e1eef2dd437f82921fe10cfdfe86>:0
  at (wrapper delegate-invoke) System.Func`1[Polly.Utilities.EmptyStruct]:invoke_TResult ()
  at Polly.Retry.RetryEngine.Implementation[TResult] (System.Func`1[TResult] action, System.Collections.Generic.IEnumerable`1[T] shouldRetryExceptionPredicates, System.Collections.Generic.IEnumerable`1[T] shouldRetryResultPredicates, System.Func`1[TResult] policyStateFactory) [0x0000e] in <1b91e1eef2dd437f82921fe10cfdfe86>:0```

**Comment by calebcall** [comment]
I'm looking in the watcher logs now to see if I can see any other reason why the connection is refused.

**Comment by calebcall** [comment]
Nothing in the logs, both plexrequests and watcher are on the same machine, so no firewall in the way.  I verified I could telnet to my watcher port number (it is a custom port) using the same address (ip address, not localhost or a hostname)

**Comment by tidusjar** [comment]
Yeah. It's probably outside of Watcher. Do you have a base URL?

**Comment by calebcall** [comment]
Yes I do.  I can configure it and test without and see if that makes a difference.

**Comment by WilliamJBrown** [comment]
Using version:    .	2.0.1184

`Unexpected character encountered while parsing value: <. Path '', line 0, position 0.`

`Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0. at Newtonsoft.Json.JsonTextReader.ParseValue () <0x4124d3c0 + 0x00497> in :0 at Newtonsoft.Json.JsonTextReader.Read () <0x4124cf40 + 0x0004b> in :0 at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () <0x4124cf00 + 0x00013> in :0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, Boolean hasConverter) <0x4124ccd0 + 0x00087> in :0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, Boolean checkAdditionalContent) <0x4124c530 + 0x000d7> in :0`

I get these errors. I have tried with or without baseurl. Not sure if again the api has changed.

**Comment by tidusjar** [comment]
Check out the latest EAP, there were more API changes in Watcher.

I've also added the label *(beta)* and a small note on the settings stating that watcher is still very much in development and it may stop working at any point... :(

**Comment by calebcall** [comment]
Thank!  Mine's working now with the latest EAP (2.0.1193)

**Comment by nosmokingbandit** [comment]
Watcher dev here.

I didn't read the entire Issue history, but if there is anything I can do PLEASE let me know. I'm happy to help is any way I can.

**Comment by WilliamJBrown** [comment]
Can confirm, working in dev release 	2.0.1191 Thanks guys :)

**Comment by tidusjar** [comment]
@nosmokingbandit is there some way to know when you change/add stuff to your API? I can't find any sort of release notes or anything.

I understand that Watcher is still very much in early development, but it would be good to keep this in mind 😄  especially if people are using the API now 😄

**Comment by nosmokingbandit** [comment]
I really don't have any good method of keeping changelogs. I probably should.

@SoundJester started a [reddit](https://www.reddit.com/r/watcher/) page for it and I'll occasionally post announcements there for important things (if I remember).

Honestly I'm just not that organized. I don't anticipate changing the API at all, just adding to it. I do try to keep the wiki updated when I change major things like this.

**Comment by tidusjar** [comment]
Maybe version the API?

**Comment by nosmokingbandit** [comment]
@tidusjar

FYI, I changes the api a bit. A while ago I added an api version to the api calls, but since this could potentially break things I want to give you a heads up.

All responses are now bools instead of string 'true'/'false'.

I don't know why I ever did it that way to begin with, but it is done correctly now.

So when you load the json into a dictionary or javascript object you'll need to test for
`x['response'] == True`

**Comment by tidusjar** [comment]
@nosmokingbandit OK thanks for the heads up! How have you added the version? 

Change in the endpoint route? `/v1/movies`?

**Comment by SuperPotatoMen** [comment]
Reopend, Api has been changed

**Comment by nosmokingbandit** [comment]
@tidusjar 
I don't want to have the old api version around at all since it was inherently flawed, so make your calls as usual.

In the future new api major versions will have a new endpoint.

**Comment by WilliamJBrown** [comment]
Can confirm not working at this point

`Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0. at Newtonsoft.Json.JsonTextReader.ParseValue () <0x4108c730 + 0x00497> in :0 at Newtonsoft.Json.JsonTextReader.Read () <0x4108bcc0 + 0x0004b> in :0 at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () <0x4108bc80 + 0x00013> in :0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, Boolean hasConverter) <0x4108ba50 + 0x00087> in :0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, Boolean checkAdditionalContent) <0x4108b390 + 0x000d7> in :0`

`Unexpected character encountered while parsing value: <. Path '', line 0, position 0.`

`Error converting value "Default" to type 'Ombi.Api.Models.Watcher.Quality'. Path 'movies[0].quality', line 18, position 23.`

`Error when trying to get Watchers movies`

**Comment by nosmokingbandit** [comment]
I think this might be my fault. That log is hard to read without proper formatting, but I'm looking into it right now.

**Comment by WilliamJBrown** [comment]
Not a problem @nosmokingbandit 

You are killing it with your bug squashing right now! below 15 last time i checked keep it up :)

**Comment by nosmokingbandit** [comment]
To be fair, a lot of those were closed because I didn't get a response back from the issuer. So I don't know if things are fixed or not...

But then again, a lot of open issues are feature requests, so I'm pretty happy about keeping things (relatively) stable.

**Comment by WilliamJBrown** [comment]
Just checked that watcher is now working with ombi again :) Thanks @nosmokingbandit 

@SuperPotatoMen @tidusjar You can now close this :)

**Comment by WilliamJBrown** [comment]
All fixed!
